Map<String, dynamic> layoutOne = {
  "company_logo": "",
  "company_name": "Dino Store",
  "company_info1": "227 Cobblestone Road",
  "company_info2": "30000 Bedrock, Cobblestone County",
  "company_info3": "+555 7 789-1234",
  "company_info4": "https://dinostore.bed | hello@dinostore.bed",
  "company_info5": "Payment details:",
  "company_info6": "ACC:123006705",
  "company_info7": "IBAN:US100000060345",
  "company_info8": "SWIFT:BOA447",
  "company_info9": "",
  "invoice_date_label": "Invoice Date:",
  "issue_date_label": "Issue Date:",
  "due_date_label": "Due Date:",
  "currency_label": "Currency:",
  "invoice_info1_label": "",
  "invoice_info1": "",
  "invoice_info2_label": "",
  "invoice_info2": "",
  "invoice_info3_label": "",
  "invoice_info3": "",
  "invoice_info4_label": "",
  "invoice_info4": "",
  "invoice_info5_label": "",
  "invoice_info5": "",
  "bill_to_label": "Bill to:",
  "bill_to_info1": "Slate Rock and Gravel Company",
  "bill_to_info2": "222 Rocky Way",
  "bill_to_info3": "30000 Bedrock, Cobblestone County",
  "bill_to_info4": "+555 7 123-5555",
  "bill_to_info5": "fred@slaterockgravel.bed",
  "invoice_title": "INVOICE",
  "invoice_number": "1",
  "invoice_number_label": "Invoice No.",
  "item_row_number_label": "SlNo",
  "item_description_label": "Item",
  "item_quantity_label": "Quantity",
  "item_price_label": "Price",
  "item_discount_label": "Discount",
  "item_tax_label": "Tax",
  "item_amount_label": "Amount",
  "amount_subtotal_label": "Subtotal:",
  "amount_subtotal": 300,
  "amount_total_label": "Total:",
  "amount_total": 357,
  "amount_paid_label": "Paid:",
  "amount_paid": 0,
  "amount_due_label": "Amount Due:",
  "amount_due": 357,
  "terms_label": "Terms & Notes",
  "terms":
      "Fred, thank you very much. We really appreciate your business.\nPlease send payments before the due date.",
  "date_format": "dd.mm.yyyy",
  "currency_code": "EUR",
  "currency_symbol": "€",
  "currency_position": "right",
  "currency_number_format": {
    "numFractionDigits": 2,
    "fractionSep": ",",
    "thousandsSep": "."
  },
  "items_columns": {
    "item_row_number": "SlNo",
    "item_description": "Item",
    "item_quantity": "Quantity",
    "item_price": "Price",
    "item_discount": "Discount",
    "item_tax": "Tax",
    "item_line_total": "Amount"
  },
  "items": [
    {
      "item_row_number": 1,
      "item_description": "Frozen Brontosaurus Ribs",
      "item_quantity": 1,
      "item_price": 100,
      "item_discount": 0,
      "item_tax": 19,
      "item_line_total": 100
    },
    {
      "item_row_number": 2,
      "item_description": "Lamb Steak",
      "item_quantity": 1,
      "item_price": 120,
      "item_discount": 0,
      "item_tax": 19,
      "item_line_total": 120
    },
    {
      "item_row_number": 3,
      "item_description": "Steamed Fish",
      "item_quantity": 1,
      "item_price": 80,
      "item_discount": 0,
      "item_tax": 19,
      "item_line_total": 80
    },
  ],
  "invoice_date": "2024-03-02",
  "issue_date": "2024-03-02",
  "due_date": "2024-04-01",
  "template_name": "template1",
  "taxes": [
    {"tax_name": "Tax 19%:", "tax_value": 57, "tax_percentage": 19}
  ]
};
